### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by sanghun92** [sanghun92/carrot-market#4]
## Description
회원 가입 기능 구현

<br>

## Todo
- [ ] 회원 도메인은 이름, 이메일주소, 비밀번호, 핸드폰 번호, 주소를 가진다.
- [ ] 이메일 주소는 중복될 수 없다.
- [ ] (option) 가입 요청시 인증 메일을 전송한다.

<br>

## ETC
민감한 정보는 암호화한다.

<br>
